"""add issue activity table

Revision ID: a58dce5198c9
Revises: 8cba7b2dba67
Create Date: 2026-09-23 12:29:37.169421

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a58dce5198c9"
down_revision: str | Sequence[str] | None = "8cba7b2dba67"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issue_activities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("issue_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "created",
                "title_changed",
                "description_changed",
                "status_changed",
                "priority_changed",
                "assignee_changed",
                name="issue_activity_event_type",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("field_name", sa.String(length=50), nullable=True),
        sa.Column("old_value", sa.String(length=255), nullable=True),
        sa.Column("new_value", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_issue_activities_created_at"), "issue_activities", ["created_at"], unique=False)
    op.create_index(op.f("ix_issue_activities_issue_id"), "issue_activities", ["issue_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_issue_activities_issue_id"), table_name="issue_activities")
    op.drop_index(op.f("ix_issue_activities_created_at"), table_name="issue_activities")
    op.drop_table("issue_activities")
    # ### end Alembic commands ###
